#!/bin/sh
### BEGIN INIT INFO
# Provides:          nessusd
# Required-Start:    $network $local_fs $remote_fs
# Required-Stop:     $network $local_fs $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts and stops the Nessus Scanner
# Description:       Starts and stops the Nessus Scanner
### END INIT INFO
#
# description: Starts and stops the Nessus Scanner
#


test -x /opt/nessus/sbin/nessus-service || {
	echo "Nessus not properly installed"
	exit 1
	}

RETVAL=0


start() {
        KIND="Nessus"
	echo -n $"Starting Nessus : "
	/opt/nessus/sbin/nessus-service -D -q
	echo "."
	return 0
}	

stop() {
	echo -n $"Shutting down Nessus : "
	test -f /opt/nessus/var/nessus/nessus-service.pid && kill `cat /opt/nessus//var/nessus/nessus-service.pid`
	echo "."
	return 0
}	

restart() {
	stop
	sleep 3
	start
}	


case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart)
  	restart
	;;
  *)
	echo $"Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
