#! /bin/sh
### BEGIN INIT INFO
# Provides:          partimaged
# Required-Start:    $remote_fs $network
# Required-Stop:     $remote_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Partition Image Server
# Description:       Partition Image Server let's you backup partitions from
#                    a client to a server.
#                    All data is transferred encrypted using SSL.
### END INIT INFO

# Author: Michael Biebl <biebl@debian.org>

DAEMON=/usr/sbin/partimaged
OPTS=""
NAME=partimaged
DESC="Partition Image Server"
PIDFILE=/var/run/partimaged.pid

test -x $DAEMON || exit 0

. /lib/lsb/init-functions

# Default configuration
TARGET=/var/lib/partimaged/

# Overwrite default configuration if available 
if [ -f /etc/default/partimaged ]; then
	. /etc/default/partimaged
fi

do_start() {
	start-stop-daemon --start --quiet --exec $DAEMON -m --pidfile $PIDFILE -b -- $OPTS -d $TARGET
}

do_stop() {
	start-stop-daemon --stop --quiet --exec $DAEMON --pidfile $PIDFILE
	RETVAL="$?"
	# Cleanup stale pid file
	rm -f $PIDFILE
	return "$RETVAL"
}

case "$1" in
  start)
	log_daemon_msg "Starting $DESC" $NAME
  	do_start
        case "$?" in
                0) log_end_msg 0 ;;
                1) log_progress_msg "already started"
                   log_end_msg 0 ;;
                *) log_end_msg $? ;;
        esac

	;;
  stop)
	log_daemon_msg "Stopping $DESC" $NAME
  	do_stop
        case "$?" in
                0) log_end_msg 0 ;;
                1) log_progress_msg "already stopped"
                   log_end_msg 0 ;;
                *) log_end_msg $? ;;
        esac

	;;
  restart|force-reload)
  	$0 stop
	$0 start
	;;
  status)
	status_of_proc -p $PIDFILE $DAEMON $NAME && exit 0 || exit $?	
	;;
  *)
	N=/etc/init.d/$NAME
	echo "Usage: $N {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0
