#!/bin/sh

DAEMON=/usr/bin/pcapdump
NAME=pcapdump

ENABLED=0

test -x $DAEMON || exit 0

test -f /etc/default/pcapdump && . /etc/default/pcapdump
             
test "$ENABLED" != "0" || exit 0
test ! -z "$INSTANCES" || exit 0

mkdir -p /var/run/pcapdump

for INSTANCE in $INSTANCES; do

    PIDFILE="/var/run/pcapdump/$INSTANCE.pid"
    OPTIONS="-C /etc/pcapdump/$INSTANCE -P $PIDFILE"

    case "$1" in
        start)
            echo -n "Starting $NAME: "
            start-stop-daemon --start --pidfile $PIDFILE \
                --name $NAME --oknodo --startas $DAEMON \
                -- $OPTIONS
            echo "$INSTANCE."
            ;;

        stop)
            echo -n "Stopping $NAME: "
            start-stop-daemon --stop --pidfile $PIDFILE --name $NAME --oknodo
            echo "$INSTANCE."
            ;;

        restart|force-reload)
            echo -n "Restarting $NAME: "
            start-stop-daemon --stop --pidfile $PIDFILE --name $NAME \
                --retry 30 --oknodo
            start-stop-daemon --start --pidfile $PIDFILE \
                --name $NAME --oknodo --startas $DAEMON \
                -- $OPTIONS
            echo "$INSTANCE."
            ;;

        *)
            N=/etc/init.d/$NAME
            echo "Usage: $N {start|stop|restart|force-reload}" >&2
            exit 1
            ;;
    esac

done

exit 0

### BEGIN INIT INFO
# Provides:          pcapdump
# Required-Start:    $network $remote_fs $syslog
# Required-Stop:     $network $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
### END INIT INFO
